In [39]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [30]:
Past_Data = pd.read_csv("Linear-Regression-_Training-Data_-.csv")
Past_Data.head()

   Purchase hybrid vehicle  Age  Education  Income  Vehicle Ownership
0                        0    4          2       4                  1
1                        0    1          2       9                  1
2                        0    1          3       7                  2
3                        1    3          4      12                  4
4                        0    2          3       7                  2

In [31]:
# Define Independent (X) and Dependend (Y)

X = Past_Data[["Age", "Education", "Income", "Vehicle Ownership"]]
Y = Past_Data["Purchase hybrid vehicle"]

In [40]:
# Train with Linear Regression

CarPre_ml = LinearRegression()
CarPre_ml.fit(X,Y)

print("Model has been trained under LINEAR REGRESSION sucessfully")

Model has been trained under LINEAR REGRESSION sucessfully

In [41]:
New_Data = pd.read_csv("Linear-Regression-Python-_Test-data_.csv")
New_Data.head()

   Age  Education  Income  Vehicle Ownership
0    3          2       8                  2
1    4          4      12                  3
2    2          3      10                  1
3    5          5      15                  4
4    1          2       5                  1

In [42]:
New_Data["Predection %"] = ((CarPre_ml.predict(New_Data))*100).round(2)
New_Data.head()

   Age  Education  Income  Vehicle Ownership  Predection %
0    3          2       8                  2         47.80
1    4          4      12                  3        108.53
2    2          3      10                  1         48.74
3    5          5      15                  4        156.74
4    1          2       5                  1         -3.35

In [43]:
New_Data.to_excel("Car Purchase Prediction_LinearRegression.xlsx", index=False)